using UnityEngine;
using System.Collections;
using System;
using System.Data;
using System.Text;
using Mono.Data.SqliteClient;

public class CreaBaseDatos : MonoBehaviour {
	void Start () {
		BaseDatos db = new BaseDatos ();
		db.AbrirBD("turismo.db");
		//crea tabla SITIO	
		string[] colSitio = {"id_sitio","nombre_sitio","escena_ra","modelo3d","dir_sitio","lat_sitio","lon_sitio","desc_sitio","traduccion"};
		string[] tiposColSitio = {"integer primary key autoincrement","text","text","text","text","text","text","text","text"};
		db.BasicQuery ("drop table if exists sitio");
		if(!db.CrearTabla("sitio", colSitio, tiposColSitio))
			Debug.Log("Error creando tabla sitio");
		// insertando datos en tabla SITIO
		string[] nomColSitio = {"nombre_sitio","escena_ra","modelo3d","dir_sitio","lat_sitio","lon_sitio","desc_sitio","traduccion"};
		//Pabellon de los Oficiales Reales
		string[] datosSitio1 = {"'Pabellón Oficiales Reales'","'PabellonOficialesReales01'","'Pabellondelosoficialesreales'","'http://goo.gl/pIHyhk'","'-19,58765'","'-65,75561'","'Fue el segundo edificio más importante después de la Casa de la Moneda, puesto que aquí desempeñaban sus funciones los Oficiales del Rey, para la administración del Quinto Real.La construcción por los elementos que presenta, pertenece a los siglos XVII y XVIII. La portada presenta una superposición de dos estilos: barroco y neoclásico, que se los puede diferenciar, debido a que este último es polícromo. Durante la Guerra de la Independencia, el edificio fue remodelado.Hoy en día, no es ya un edificio administrativo y se ha rehabilitado como vivienda social, para 12 familias y se constituye en el primer ejemplo en Bolivia, de aprovechamiento de un edificio patrimonial, para esta función.Se encuentra en la esquina que forman las calles Bolívar y Oruro.'","'It was the second most important building after the Money House, since here the Kings officers performed their work, for the administration of Quinto Real.Because of its elements, the construction belongs to the XVII and XVIII centuries. The front of the building has two styles: baroque and neoclassical, which can be differentiated because the latter is polychromatic. During the Independence War, the building was remodeled.Today, it is no longer an administrative building and has been restored as social housing for 12 families and it constitutes the first heritage building in Bolivia that performs this function. It is located on the corner of Bolivar and the Oruro streets.'"};
		db.insertarEnTablaX ("sitio",nomColSitio,datosSitio1);
		//La Catedral
		string[] datosSitio2 = {"'La Catedral'","'catedralPotosi_0001'","'Catedral_Potosi'","'http://goo.gl/8z0V52'","'-19,58878'","'-65,75339'","'La primera construcción de adobe, llamada Iglesia Matriz, se desplomó el 16 de febrero de 1807 y la que vemos en la actualidad corresponde a una segunda construcción.La actual catedral, es obra del Arq. Manuel de Sanahuja, obra que se inició en 1808, inaugurándose en 1836. Es un magnífico templo, considerado como uno de los más bellos ejemplares, en la serie de las grandes catedrales latinoamericanas. En la actualidad, está en proceso de restauración. La puerta posterior de la Catedral, da a la calle Matos, denominada así en homenaje al patriota potosino Salvador Matos, calle que se denominaba de la Chicha infestada de demonios porque la gente se embriagaba en ella. También fue denominada de la Amargura y de la Expiación o del Castigo'","'The first construction with adobe, called Mother Church, it collapsed on February 16, 1807 and the building we see today corresponds to a second construction.The actual cathedral was designed by the Arq. Manuel de Sanahuja, the construction began in 1808, it was inaugurated in 1836. It is a magnificent temple, considered as one of the most beautiful examples in the series of large Latin American cathedrals. Currently, it is undergoing a restoration process.The back door of the Cathedral overlooks to the Matos street, called this way in honor to a patriot from Potosí Salvador Matos, the street once had as name Calle de la Chicha infested with demons because people got drunk there. It was also called the Bitterness Street and Expiation Street or Punishment Street.'"};
		db.insertarEnTablaX ("sitio",nomColSitio,datosSitio2);
		//La Merced
		string[] datosSitio3 = {"'La Merced'","'LaMerced01'","'la-merced'","'http://goo.gl/4QsaQc'","'-19,58869'","'-65,7517'","'Este primer y único convento de Mercedarios, fue fundado en Potosí en 1555, cuyo templo fue concluido en 1687. Los dos elementos más destacados de la iglesia, son su impresionante artesanado de carácter mudéjar (de influencia árabe) y las muestras de pintura mural, en el coro alto, son de tipo grisalla (de colores grisáceos), evidenciando la pintura mural más antigua del área andina. La nave principal conserva pintura mural del siglo XVII – XVIII – XIX, e inclusive, muestras de principios del siglo XX.'","'This first and unique Mercedarios convent, it was founded in Potosi in 1555, the temple was completed in 1687.The two most important elements in the church are its impressive craftworks with Mudejar character (of Arab influence) and the samples of mural painting in the high choir, they are grisaille type (gray color), showing the oldest mural painting of Andina area. The main church ship preserves mural painting of XVII century - XVIII - XIX, and even samples of the early twentieth century.'"};
		db.insertarEnTablaX ("sitio",nomColSitio,datosSitio3);
		//Jerusalen
		string[] datosSitio4 = {"'Jerusalén'","'Jerusalen01'","'jerusalen'","'http://goo.gl/kgCXzL'","'-19,58499'","'-65,75692'","'Este fue el único edificio religioso que no fue construido como convento, ni como parroquia de indios; sino, simplemente como un santuario, para la devoción ala Virgen de la Candelaria, aparecida en 1623 y que aún se conserva hasta nuestros días en su interior.La construcción definitiva, data de 1702. El templo fue inaugurado en 1708, con el nombre de Nuestra Señora de Jerusalén.La última restauración del edificio, finalizó el año 1997 y desde entonces, además de celebrarse oficios religiosos, funciona también como museo.El museo de Jerusalén presenta un magnífico retablo de 1769 y una interesante marquetería, que encuadra una verdadera pinacoteca, con temas relacionados a la pasión de Cristo, como también cuadros alegóricos los cuales conforman un museo singular, que relata el proceso de la Evangelización en Potosí.Se encuentra al final de la calle Oruro, que en otra época, tenía el nombre de El Rastro porque según la historia, un martes de Carnaval de 1681, un grupo de Vicuñas huyendo de sus enemigos los Vascongados.'","'This was the only religious building that was not built as a convent or Indians parish either; but simply as a sanctuary for devotion to the Virgen de la Candelaria, she appeared in 1623 and is still preserved until today, inside the temple.The final construction dates back to 1702. The temple was inaugurated in 1708, with the name of Our Lady of Jerusalem.The last building restoration was completed in 1997 and since then religious services are celebrated there and also it is used as a museum.'"};
		db.insertarEnTablaX ("sitio",nomColSitio,datosSitio4);
		//Teatro Modesto Omiste
		string[] datosSitio5 = {"'Teatro Modesto Omiste'","'TeatroModestoOmiste01'","'Modesto-Omiste'","'http://goo.gl/2iz8eS'","'-19,58882'","'-65,75278'","'La orden religiosa de los Betlemitas, ingresó a Potosí en el año de 1700. Dado que su finalidad era el cuidado de hospitales, se les entregó el Hospital Real de la Vera Cruz, que en 1826, se convirtió en el Colegio Nacional Pichincha, fundado por el Mariscal Antonio José de Sucre.La antigua capilla de desplomó en 1725, debido a fuertes lluvias. Ese mismo año se inició la construcción de la nueva iglesia, trabajo que se encargó al Arq. Bernardo Rojas y  Saldaña, que la concluyó en 1753.En 1823, durante la Guerra de la Independencia, las torres de la iglesia, fueron destruidas para, en su lugar, emplazar cañones, y el convento se convirtió en cuartel. En 1850, se decreta que la iglesia de Belén se convierta en Teatro y a partir de 1862, recién cumple esta función. En el siglo XX, se convierte en cine y hoy, nuevamente funciona como Teatro, luego de su rehabilitación en 1994, obra que mereció el primer Premio de la Junta de Andalucía en la IX Bienal Panamericana de Arquitectura de Quito, en 1994.'","'The Betlemitas religious order, arrived to Potosi in the year 1700. As its purpose was to care hospitals, they were given the Royal Hospital de la Vera Cruz, which in 1826 it became into the Colegio Nacional Pichincha, founded by Marshal Antonio Jose de Sucre.The old chapel collapsed in 1725 due to strong rains. That same year the construction of the new church began, the Arq. Bernardo Rojas y Saldaña was in charge of this work, and it was completed in 1753.In 1823, during the Independence War, the church towers were destroyed and instead of them, were placed cannons, and the convent became into barracks. In 1850, it decreed that Belen church becomes into theater and from 1862 newly performs this function. In the twentieth century, it became into a cinema and today works as theater again, after its rehabilitation in 1994, it won the first prize of the Board of Andalusian in the IX Pan American Architecture Biennial of Quito, in 1994.'"};
		db.insertarEnTablaX ("sitio",nomColSitio,datosSitio5);
		//San Agustin
		string[] datosSitio6 = {"'San Agustin'","'SanAgustin01'","'san-agustin'","'http://goo.gl/jjMj7J'","'-19,58754'","'-65,75385'","'La iglesia, capilla y convento de Nuestra Señora de Aranzazu (San Agustín), patrona de los vascongados, data del siglo XVII. Lo único que queda, es la portada de estilo renacentista. Interiormente se aprecia imágenes talladas por Gaspar de la Cueva. En este templo, se venera a San José.Se encuentra entre las calles Quijarro, antes de la Ollería y Bolivar, antes de los Césares por recordar a los emperadores romanos.'","'The church, chapel and convent of Our Lady of Aranzazu (San Augustin), patron saint of Vascongados, dates back from the XVII century. The only thing left is the cover of Renaissance style. Inside there can be seen carved images by Gaspar de la Cueva. In this temple is worshiped San Jose.It is between Quijarro (called before Ollería Street) and Bolivar streets (called before Cesares Street for remember the Roman emperors).'"};
		db.insertarEnTablaX ("sitio",nomColSitio,datosSitio6);
		//San Lorenzo
		string[] datosSitio7 = {"'San Lorenzo'","'SanLorenzo01'","'san-lorenz'","'http://goo.gl/jjMj7J'","'-19,58691'","'-65,75481'","'El primer nombre de este templo fue de La Anunciación. Fue el primer templo destinado con exclusividad a los españoles.San Lorenzo inició su construcción en 1548 y debido a una fuerte nevada, se desplomó en 1557. Fue reparada y a la llegada del Virrey Toledo, mediante Ordenanza, fue nominada como primera Iglesia Matriz. Posteriormente, construida La Catedral, pasó a ser parroquia de indígenas, cambiando el nombre por el de San Lorenzo de Carangas.Se ubica actualmente en la calle Héroes del Chaco esquina Bustillos.'","'The first name of this temple was The Annunciation. It was the first temple destined exclusively to the Spanish people.San Lorenzo began its construction in 1548 and due to a strong snowfall, it collapsed in 1557. After that It was repaired and when the Virrey Toledo arrived to the city, by Ordinance, it was nominated as the first Mother Church. Subsequently, it built the Cathedral, and San Lorenzo became in indigenous parish, changing its name to San Lorenzo de Carangas.Today it is placed on the corner of Heroes del Chaco Bustillos streets.'"};
		db.insertarEnTablaX ("sitio",nomColSitio,datosSitio7);
		//San Sebastian
		string[] datosSitio8 = {"'San Sebastian'","'SanSebastian01'","'san-sebastian'","'http://goo.gl/lxn3j0'","'-19,59272'","'-65,74981'","'Fue edificada en 1581 para los mitayos de Quillacas. En 1725 se estrenó la cúpula de media naranja sobre el crucero, tal como aparece hoy en día. Interiormente conserva el coro alto, el retablo mayor y el púlpito tallado en madera. Presenta una torre espadaña exenta, que se levanta sobre la puerta de entrada al atrio. Esta iglesia, fue restaurada por última vez el año 2001.Se halla ubicada en calle Betanzos.'","'It was built in 1581 for Mitayos de Quillacas (Mitayo kind of indigene slave). In 1725 the semicircular dome upon the crossing was completed, as it appears today. Inwardly it preserves the high choir, the main altarpiece and the pulpit carved in wood. It also presents a bulrush tower, rising above the door entrance to the atrium. This church was restored last time in 2001.It is located in Betanzos street.'"};
		db.insertarEnTablaX ("sitio",nomColSitio,datosSitio8);
		//Santa Barbara
		string[] datosSitio9 = {"'Santa Barbara'","'SantaBarbara01'","'SantaBarbara'","'http://goo.gl/jxGY5R'","'-19,59204'","'-65,75806'","'El templo de Santa Bárbara, fue la primera parroquia de indígenas. Se construyo entre 1548 y 1552, quedando actualmente solo la torre, cuya estructura es de adobe con base cuadrada. Estuvo destinada a los indígenas Omasuyos.Se ubica en la actual calle Taborga.'","'The Santa Barbara church, was the first parish of Indians. It was built between 1548 and 1552, and now only remains its tower, whose structure has a square base made of adobe. It was destined to the Omasuyos indigenous.It is located in the current Taborga Street.'"};
		db.insertarEnTablaX ("sitio",nomColSitio,datosSitio9);
		//San Francisco
		string[] datosSitio10 = {"'San Francisco'","'SanFrancisco01'","'SanFransico'","'http://goo.gl/jxGY5R'","'-19,59106'","'-65,75305'","'El convento de San Francisco, así denominado en honor a San Antonio a Padua, fue fundado en 1547 por Fray Gaspar de Velarde. Se trata del claustro más antiguo que se conserva en Bolivia. La iglesia, es una de las tres primeras que se construyen en Potosí (1547). En 1707 se iniciaron las obras de la nueva iglesia, demoliendo la antigua. Fue inaugurada en 1726.El templo y el claustro funcionan también como museo y en él, sobresalen cuadros de Gregorio Gamarra, sobre la vida de San Francisco de Asís, esculturas de Gaspar de la Cueva, pinturas de Melchor Pérez Holguín y la imagen del Cristo de la Vera Cruz, patrono de los feligreses potosinos.Desde el mirador, llamado Santa María de los Ángeles a, 4100 m.s.n.m., se admira el fabuloso paisaje potosino.San Francisco, se encuentra ubicado entre la calle Tarija, antes, Del Empedradillo, por ser la primera arteria en ser empedrado con piedras pequeñas; y la calle Nogales, antes Cantu Mayu.'","'The San Francisco convent, named this way in honor of San Antonio Padua, was founded in 1547 by Fray Gaspar de Velarde. It is the oldest cloister preserved in Bolivia.The church is one of the first three built in Potosi (1547). In 1707 the construction of the new church began, the old was demolished. It was inaugurated in 1726.The church and cloister also work as a museum and inside it can be seen pictures of Gregorio Gamarra, about the life of San Francisco de Asís, sculptures of Gaspar de la Cueva, paintings of Melchor Perez Holguin and the image of the Cristo de la Vera Cruz, patron saint of Potosinos parishionersFrom the scenic overlook, called Santa Maria de los Angeles located at an altitude of  4100 meters, can be admired the Potosino fabulous landscape.San Francisco is located between the Tarija street (called before Del Empedradillo, because it was the first street covered with small stones) and Nogales Street (called before Cantu Mayu).'"};
		db.insertarEnTablaX ("sitio",nomColSitio,datosSitio10);
		//Arco de Cobija
		string[] datosSitio11 = {"'Arco de Cobija'","'ArcodeCobija01'","'arco-de-cobija-fin'","'http://goo.gl/cnfzAs'","'-19,58978'","'-65,75644'","'Ubicada en la calle Cobija, servía de límite entre las áreas española e indígena de la ciudad. Su nombre se debe al puerto marítimo colonial de la Audiencia de Charcas, Magdalena de Cobija.'","'Placed in Cobija Street, It was used as limit between Spanish and indigenous areas of the city, Its name is due to the Charcas Audience colonial seaport, “Magdalena de Cobija”.'"};
		db.insertarEnTablaX ("sitio",nomColSitio,datosSitio11);

		db.CerrarBD();
	}
}
